### ISSUE TITLE
panic: Storm failed to initialise: EOF

### ISSUE THREAD

**Issue by rcadena** [jsgilmore/gostorm#18]
I'm trying to get a simple Spout running in a local storm installation.  The spout is very simple and basically just implements stubs for the required interface:

```go
var Log = log.NewLogger(os.Stderr, "", 0) // just in case stdout collided with shell IO

type EventSpout struct {}

func (s *EventSpout) NextTuple() {
    Log.Println("Next Tuple")
}

func (s *EventSpout) Acked(id string) {
    Log.Printf("Acked %s\n\r", id) 
}

func (s *EventSpout) Failed(id string) {
    Log.Printf("Failed: %s\n\r", id) 
}

func (s *EventSpout) Exit() {
    Log.Println("Exit")
}

func (s *EventSpout) Open(context *stormmsg.Context, collector storm.SpoutOutputCollector) {
   Log.Println("Open")
}
```

I build the binary then submit to storm as follows:

```
./bin/storm shell resources/ ~/[path-to-bin]/simplespout 
```

The log shows that the topology was successfully submitted:

```
805  [main] INFO  backtype.storm.StormSubmitter - Uploading topology jar stormshell6100219.jar to assigned location: storm-local/nimbus/inbox/stormjar-fab538f7-68ae-41df-ab1a-5a780c6b45b1.jar
814  [main] INFO  backtype.storm.StormSubmitter - Successfully uploaded topology jar to assigned location: storm-local/nimbus/inbox/stormjar-fab538f7-68ae-41df-ab1a-5a780c6b45b1.jar
```
But, I immediately get the following from `simplespout`:
```
panic: Storm failed to initialise: EOF
```

Here's the stack trace:

```
goroutine 1 [running]:
github.com/jsgilmore/gostorm/core.(*stormConnImpl).Connect(0xc82009eff0)
	/Users/rcadena/go/src/github.com/jsgilmore/gostorm/core/conns.go:105 +0x188
github.com/jsgilmore/gostorm.(*shellSpoutImpl).Initialise(0xc82009f020, 0xd60760, 0xc82009cfb0)
	/Users/rcadena/go/src/github.com/jsgilmore/gostorm/shellspout.go:45 +0x66
github.com/jsgilmore/gostorm.RunSpout(0xd60680, 0x772880, 0x500590, 0xb)
	/Users/rcadena/go/src/github.com/jsgilmore/gostorm/storm.go:69 +0x19a
main.startSpout()
	/Users/rcadena/simplespout/simplespout.go:15 +0x85
main.run(0x74a2a0, 0xc8200ae550, 0x3, 0x5)
	/Users/rcadena/simplespout/simplespout.go:10 +0x1c
main.main()
	/Users/rcadena/simplespout/simplespout.go:22 +0x23
```

Storm: 0.9.6
gostorm: commit  number 333313

Thanks in advance.  I'm new to storm.  The topology only has a spout, no bolts.  I wanted to get that part running at least.

**Comment by rcadena** [comment]
Just an update.  I've started running on storm 0.10.0 and this is no longer an issue.

**Comment by jsgilmore** [comment]
I've added a note that specifies GoStorm now required 0.10.0 or later.
